export enum ErrorsEnum {
	MissingData = 1,
	InvalidData,
	InvalidUsername,
	InvalidEmail,
	InvalidPassword,
	AccountFoundUsername,
	AccountFoundEmail,
	AccountNotFoundEmail,
	AccountNotFound,
	WrongCredentials,
	UserLocked,
	FileTooLarge,
	InternalServerError,
	InvalidEnum,
}
